Repository Gravitalia/Autha, pull requests merged in 2024-01, with the labels that each got.

#252 doc: add clippy lint and add missing doc
  autha/src/main.rs
  crypto/src/lib.rs
  db/src/scylla.rs
  image_processor/src/exif.rs
  image_processor/src/host/mod.rs
  image_processor/src/lib.rs
Labels: documentation, rust

#253 feat: Add initial Nix flake configuration
  flake.lock
  flake.nix
Labels: enhancement

#255 cd: add docker pusher with rules_oci
  .github/workflows/bazel.yml
  WORKSPACE
  autha/BUILD.bazel
Labels: enhancement

#260 chore: remove linux/amd64
  WORKSPACE
  autha/BUILD.bazel
Labels: enhancement

#268 doc: add missing documentation
  db/src/lib.rs
  image_processor/src/host/cloudinary.rs
Labels: documentation, rust

#269 fix: get age function works again
  Cargo.Bazel.lock
  Cargo.lock
  autha/Cargo.toml
  autha/src/helpers/mod.rs
Labels: bug, rust

#270 chore: newer memcache pool manager
  Cargo.Bazel.lock
  Cargo.lock
  db/Cargo.toml
  db/src/memcache/mod.rs
  db/src/memcache/pool.rs
Labels: enhancement

#272 fix: better UI/UX in front
  front/components/FontBubbles.vue
  front/package.json
  front/pages/signin.vue
  front/uno.config.ts
  front/yarn.lock
Labels: enhancement, front

#275 feat: better responsiveness
  front/components/LabelError.vue
  front/pages/signin.vue
  front/pages/signup.vue
  front/uno.config.ts
Labels: front

#271 feat: add kafka broker
  Cargo.Bazel.lock
  Cargo.lock
  autha/src/main.rs
  autha/src/model/config.rs
  db/Cargo.toml
  db/src/broker/kafka/mod.rs
  db/src/broker/kafka/pool.rs
  db/src/broker/mod.rs
  db/src/lib.rs
Labels: enhancement, rust

#278 fix: optimize ram
  autha/src/main.rs
  db/src/broker/mod.rs
Labels: rust

#279 feat: add rabbitmq support
  Cargo.Bazel.lock
  Cargo.lock
  autha/src/main.rs
  config.yaml
  db/Cargo.toml
  db/src/broker/mod.rs
  db/src/broker/rabbitmq/mod.rs
  db/src/broker/rabbitmq/pool.rs
Labels: enhancement, rust

#283 feat: improve UI/UX
  front/.gitignore
  front/locales/en-US.json
  front/locales/fr-FR.json
  front/nuxt.config.ts
  front/pages/signin.vue
  front/pages/signup.vue
Labels: front

#281 feat: add telemetry (prometheus, jaeger)
  .deepsource.toml
  .rustfmt.toml
  Cargo.Bazel.lock
  Cargo.lock
  autha/Cargo.toml
  autha/src/helpers/mod.rs
  autha/src/helpers/telemetry.rs
  autha/src/main.rs
  autha/src/model/config.rs
  autha/src/router/mod.rs
  autha/src/router/users.rs
  config.yaml
  db/src/broker/mod.rs
  db/src/scylla.rs
  docker-compose.yml
Labels: enhancement, rust, telemetry

#287 chore: remove overhead tracing variable
  autha/src/main.rs
  autha/src/router/mod.rs
  autha/src/router/users.rs
Labels: rust, telemetry

#288 feat: database deactivation option
  Cargo.Bazel.lock
  Cargo.lock
  autha/BUILD.bazel
  autha/Cargo.toml
  autha/src/main.rs
  autha/src/router/users.rs
  db/BUILD.bazel
  db/Cargo.toml
  db/src/broker/kafka/mod.rs
  db/src/broker/mod.rs
  db/src/broker/rabbitmq/mod.rs
  db/src/broker/rabbitmq/pool.rs
  db/src/lib.rs
  db/src/memcache/mod.rs
  db/src/memcache/pool.rs
  db/src/scylla.rs
Labels: enhancement, rust
